# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4c74e53a65418549381dcdd6d8025f02a9fa699daeb31138789554597f04b3015a303a309b07dfbfb545e1c774f65afbee4e371864310e533f6e76ccf83fe06d

test:
  secret_key_base: 1961a42cb0d3f18e8f54a85bbe598cef7ad1005ad8d8b8efde503aeee5af726aa3325958f1c5e6140c4604b3e24d242b70d3297bdbc209844ab529024a5e00f8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
